# Generated by Django 4.2.6 on 2023-10-31 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='monitoria.curso'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='monitoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoria.monitoria'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
