# Generated by Django 4.2.6 on 2023-10-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoria', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoria',
            old_name='tipo',
            new_name='tipo_monitoria',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
