# Generated by Django 4.2.4 on 2023-09-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0003_pontuacao_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pontuacao', models.PositiveIntegerField()),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.PositiveIntegerField()),
                ('valor_por_hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.TextField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorias.disciplina')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Pontuacao',
        ),
        migrations.AddField(
            model_name='monitoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorias.usuario'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='monitoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorias.monitoria'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorias.usuario'),
        ),
    ]
